[terminal]
shell = '/usr/bin/fish'

[general]
import = [
    "~/.config/alacritty/themes/moonfly.toml"
]

[window]
startup_mode = "Maximized"
decorations  = "None"

[font]
normal = { family = "Caskaydia Mono Nerd Font", style = "Regular" }
size = 14
